using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PAYONEER.RandomData
{
    public class Answer_Question_Cate_02_Name
    {
        public string Get_Name () 
        {
            List<string> list_name = new List<string>();

            list_name.Add("an duong");  // 01
            list_name.Add("an khe");  // 02
            list_name.Add("bac giang");  // 10
            list_name.Add("bac ha");  // 11
            list_name.Add("bac me");  // 12
            list_name.Add("bac ninh");  // 13
            list_name.Add("bac quang");  // 14
            list_name.Add("bac son");  // 15
            list_name.Add("bac tan uyen");  // 16
            list_name.Add("bac yen");  // 17
            list_name.Add("bach thong");  // 18
            list_name.Add("bao lac");  // 19
            list_name.Add("bao lam");  // 20
            list_name.Add("bao loc");  // 21
            list_name.Add("bao thang");  // 22
            list_name.Add("bao yen");  // 23
            list_name.Add("bau bang");  // 24
            list_name.Add("ben cat");  // 25
            list_name.Add("bien hoa");  // 26
            list_name.Add("bim son");  // 27
            list_name.Add("binh gia");  // 28
            list_name.Add("binh giang");  // 29
            list_name.Add("binh lieu");  // 30
            list_name.Add("binh long");  // 31
            list_name.Add("binh luc");  // 32
            list_name.Add("binh minh");  // 33
            list_name.Add("binh tan");  // 34
            list_name.Add("binh xuyen");  // 35
            list_name.Add("bu dang");  // 36
            list_name.Add("bu dop");  // 37
            list_name.Add("bu gia map");  // 38
            list_name.Add("buon don");  // 39
            list_name.Add("buon ho");  // 40
            list_name.Add("cam giang");  // 41
            list_name.Add("cam khe");  // 42
            list_name.Add("cam my");  // 43
            list_name.Add("cam pha");  // 44
            list_name.Add("cam thuy");  // 45
            list_name.Add("cam xuyen");  // 46
            list_name.Add("can loc");  // 47
            list_name.Add("cao bang");  // 48
            list_name.Add("cao loc");  // 49
            list_name.Add("cao phong");  // 50
            list_name.Add("cat hai");  // 51
            list_name.Add("cat tien");  // 52
            list_name.Add("chi lang");  // 53
            list_name.Add("chi linh");  // 54
            list_name.Add("chiem hoa");  // 55
            list_name.Add("cho don");  // 56
            list_name.Add("cho moi");  // 57
            list_name.Add("chon thanh");  // 58
            list_name.Add("di an");  // 59
            list_name.Add("di linh");  // 60
            list_name.Add("dien bien");  // 61
            list_name.Add("dien bien dong");  // 62
            list_name.Add("dien bien phu");  // 63
            list_name.Add("dinh hoa");  // 64
            list_name.Add("dinh lap");  // 65
            list_name.Add("dinh quan");  // 66
            list_name.Add("do son");  // 67
            list_name.Add("doan hung");  // 68
            list_name.Add("don duong");  // 69
            list_name.Add("dong hoa");  // 70
            list_name.Add("dong hung");  // 71
            list_name.Add("dong hy");  // 72
            list_name.Add("dong phu");  // 73
            list_name.Add("dong son");  // 74
            list_name.Add("dong trieu");  // 75
            list_name.Add("dong van");  // 76
            list_name.Add("dong xoai");  // 77
            list_name.Add("dong xuan");  // 78
            list_name.Add("duc tho");  // 79
            list_name.Add("duc trong");  // 80
            list_name.Add("duong kinh");  // 81
            list_name.Add("duy tien");  // 82
            list_name.Add("gia binh");  // 83
            list_name.Add("gia loc");  // 84
            list_name.Add("gia nghia");  // 85
            list_name.Add("gia vien");  // 86
            list_name.Add("giao thuy");  // 87
            list_name.Add("ha giang");  // 88
            list_name.Add("ha hoa");  // 89
            list_name.Add("ha lang");  // 90
            list_name.Add("ha long");  // 91
            list_name.Add("ha quang");  // 92
            list_name.Add("ha tinh");  // 93
            list_name.Add("ha trung");  // 94
            list_name.Add("hai an");  // 95
            list_name.Add("hai duong");  // 96
            list_name.Add("hai ha");  // 97
            list_name.Add("hai hau");  // 98
            list_name.Add("ham yen");  // 99
            list_name.Add("hau loc");  // 100
            list_name.Add("hiep hoa");  // 101
            list_name.Add("hoa an");  // 102
            list_name.Add("hoa binh");  // 103
            list_name.Add("hoa lu");  // 104
            list_name.Add("hoang hoa");  // 105
            list_name.Add("hon quan");  // 106
            list_name.Add("hong bang");  // 107
            list_name.Add("hong linh");  // 108
            list_name.Add("hung ha");  // 109
            list_name.Add("hung yen");  // 110
            list_name.Add("huong khe");  // 111
            list_name.Add("huong son");  // 112
            list_name.Add("huu lung");  // 113
            list_name.Add("kbang");  // 114
            list_name.Add("khoai chau");  // 115
            list_name.Add("kien an");  // 116
            list_name.Add("kien thuy");  // 117
            list_name.Add("kien xuong");  // 118
            list_name.Add("kim bang");  // 119
            list_name.Add("kim boi");  // 120
            list_name.Add("kim dong");  // 121
            list_name.Add("kim son");  // 122
            list_name.Add("kim thanh");  // 123
            list_name.Add("kinh mon");  // 124
            list_name.Add("ky anh");  // 125
            list_name.Add("lac duong");  // 126
            list_name.Add("lac son");  // 127
            list_name.Add("lac thuy");  // 128
            list_name.Add("lai chau");  // 129
            list_name.Add("lam binh");  // 130
            list_name.Add("lam ha");  // 131
            list_name.Add("lam thao");  // 132
            list_name.Add("lang chanh");  // 133
            list_name.Add("lang giang");  // 134
            list_name.Add("lang son");  // 135
            list_name.Add("lao cai");  // 136
            list_name.Add("lap thach");  // 137
            list_name.Add("le chan");  // 138
            list_name.Add("loc binh");  // 139
            list_name.Add("loc ha");  // 140
            list_name.Add("loc ninh");  // 141
            list_name.Add("long ho");  // 142
            list_name.Add("long khanh");  // 143
            list_name.Add("long thanh");  // 144
            list_name.Add("luc nam");  // 145
            list_name.Add("luc ngan");  // 146
            list_name.Add("luc yen");  // 147
            list_name.Add("luong son");  // 148
            list_name.Add("luong tai");  // 149
            list_name.Add("ly nhan");  // 150
            list_name.Add("mai chau");  // 152
            list_name.Add("mai son");  // 153
            list_name.Add("mang thit");  // 154
            list_name.Add("moc chau");  // 157
            list_name.Add("mong cai");  // 158
            list_name.Add("muong khuong");  // 162
            list_name.Add("muong la");  // 163
            list_name.Add("muong lat");  // 164
            list_name.Add("muong lay");  // 165
            list_name.Add("muong nhe");  // 166
            list_name.Add("muong te");  // 167
            list_name.Add("my hao");  // 168
            list_name.Add("my loc");  // 169
            list_name.Add("na hang");  // 170
            list_name.Add("nam dinh");  // 172
            list_name.Add("nam nhun");  // 173
            list_name.Add("nam sach");  // 175
            list_name.Add("nam truc");  // 176
            list_name.Add("nga son");  // 177
            list_name.Add("ngan son");  // 178
            list_name.Add("nghi son");  // 179
            list_name.Add("nghi xuan");  // 180
            list_name.Add("nghia hung");  // 181
            list_name.Add("nghia lo");  // 182
            list_name.Add("ngo quyen");  // 183
            list_name.Add("ngoc hoi");  // 184
            list_name.Add("ngoc lac");  // 185
            list_name.Add("nguyen binh");  // 186
            list_name.Add("nho quan");  // 187
            list_name.Add("nhon trach");  // 188
            list_name.Add("nhu thanh");  // 189
            list_name.Add("nhu xuan");  // 190
            list_name.Add("ninh binh");  // 191
            list_name.Add("ninh giang");  // 192
            list_name.Add("ninh hai");  // 193
            list_name.Add("ninh phuoc");  // 194
            list_name.Add("ninh son");  // 195
            list_name.Add("pho yen");  // 198
            list_name.Add("phong tho");  // 199
            list_name.Add("phu binh");  // 200
            list_name.Add("phu cu");  // 201
            list_name.Add("phu giao");  // 202
            list_name.Add("phu hoa");  // 203
            list_name.Add("phu luong");  // 204
            list_name.Add("phu ly");  // 205
            list_name.Add("phu ninh");  // 206
            list_name.Add("phu rieng");  // 207
            list_name.Add("phu thien");  // 208
            list_name.Add("phu tho");  // 209
            list_name.Add("phu yen");  // 210
            list_name.Add("phuc yen");  // 211
            list_name.Add("phuoc long");  // 212
            list_name.Add("quan ba");  // 213
            list_name.Add("quan hoa");  // 214
            list_name.Add("quan son");  // 215
            list_name.Add("quang binh");  // 216
            list_name.Add("quang hoa");  // 217
            list_name.Add("quang xuong");  // 218
            list_name.Add("quang yen");  // 219
            list_name.Add("que vo");  // 220
            list_name.Add("quynh nhai");  // 221
            list_name.Add("quynh phu");  // 222
            list_name.Add("sa thay");  // 223
            list_name.Add("sam son");  // 224
            list_name.Add("sin ho");  // 226
            list_name.Add("son dong");  // 227
            list_name.Add("son duong");  // 228
            list_name.Add("son hoa");  // 229
            list_name.Add("son la");  // 230
            list_name.Add("song cau");  // 231
            list_name.Add("song cong");  // 232
            list_name.Add("song hinh");  // 233
            list_name.Add("song lo");  // 234
            list_name.Add("song ma");  // 235
            list_name.Add("sop cop");  // 236
            list_name.Add("tam binh");  // 237
            list_name.Add("tam dao");  // 238
            list_name.Add("tam diep");  // 239
            list_name.Add("tam duong");  // 240
            list_name.Add("tam nong");  // 241
            list_name.Add("tan lac");  // 242
            list_name.Add("tan phu");  // 243
            list_name.Add("tan son");  // 244
            list_name.Add("tan uyen");  // 245
            list_name.Add("tan yen");  // 246
            list_name.Add("tay hoa");  // 247
            list_name.Add("thach an");  // 248
            list_name.Add("thach ha");  // 249
            list_name.Add("thach thanh");  // 250
            list_name.Add("thai binh");  // 251
            list_name.Add("thai nguyen");  // 252
            list_name.Add("thai thuy");  // 253
            list_name.Add("than uyen");  // 254
            list_name.Add("thanh ba");  // 255
            list_name.Add("thanh ha");  // 256
            list_name.Add("thanh hoa");  // 257
            list_name.Add("thanh liem");  // 258
            list_name.Add("thanh mien");  // 259
            list_name.Add("thanh son");  // 260
            list_name.Add("thanh thuy");  // 261
            list_name.Add("thieu hoa");  // 262
            list_name.Add("tho xuan");  // 263
            list_name.Add("thong nhat");  // 264
            list_name.Add("thu dau mot");  // 265
            list_name.Add("thuan an");  // 266
            list_name.Add("thuan bac");  // 267
            list_name.Add("thuan chau");  // 268
            list_name.Add("thuan nam");  // 269
            list_name.Add("thuan thanh");  // 270
            list_name.Add("thuong xuan");  // 271
            list_name.Add("thuy nguyen");  // 272
            list_name.Add("tien du");  // 273
            list_name.Add("tien hai");  // 274
            list_name.Add("tien lang");  // 275
            list_name.Add("tien lu");  // 276
            list_name.Add("tien yen");  // 277
            list_name.Add("tra on");  // 278
            list_name.Add("tram tau");  // 279
            list_name.Add("tran yen");  // 280
            list_name.Add("trang bom");  // 281
            list_name.Add("trang dinh");  // 282
            list_name.Add("trieu son");  // 283
            list_name.Add("truc ninh");  // 284
            list_name.Add("trung khanh");  // 285
            list_name.Add("tu ky");  // 286
            list_name.Add("tu mo rong");  // 287
            list_name.Add("tu son");  // 288
            list_name.Add("tua chua");  // 289
            list_name.Add("tuan giao");  // 290
            list_name.Add("tuy an");  // 291
            list_name.Add("tuy duc");  // 292
            list_name.Add("tuy hoa");  // 293
            list_name.Add("tuyen quang");  // 294
            list_name.Add("van ban");  // 296
            list_name.Add("van chan");  // 297
            list_name.Add("van don");  // 298
            list_name.Add("van giang");  // 299
            list_name.Add("van ho");  // 300
            list_name.Add("van lam");  // 301
            list_name.Add("van lang");  // 302
            list_name.Add("van quan");  // 303
            list_name.Add("van yen");  // 304
            list_name.Add("vi xuyen");  // 305
            list_name.Add("viet tri");  // 306
            list_name.Add("viet yen");  // 307
            list_name.Add("vinh bao");  // 308
            list_name.Add("vinh cuu");  // 309
            list_name.Add("vinh loc");  // 310
            list_name.Add("vinh long");  // 311
            list_name.Add("vinh tuong");  // 312
            list_name.Add("vinh yen");  // 313
            list_name.Add("vo nhai");  // 314
            list_name.Add("vu ban");  // 315
            list_name.Add("vu quang");  // 316
            list_name.Add("vu thu");  // 317
            list_name.Add("vung liem");  // 318
            list_name.Add("xin man");  // 319
            list_name.Add("xuan loc");  // 320
            list_name.Add("xuan truong");  // 321
            list_name.Add("yen bai");  // 322
            list_name.Add("yen binh");  // 323
            list_name.Add("yen chau");  // 324
            list_name.Add("yen dinh");  // 325
            list_name.Add("yen dung");  // 326
            list_name.Add("yen khanh");  // 327
            list_name.Add("yen lac");  // 328
            list_name.Add("yen lap");  // 329
            list_name.Add("yen minh");  // 330
            list_name.Add("yen my");  // 331
            list_name.Add("yen phong");  // 332
            list_name.Add("yen son");  // 333
            list_name.Add("yen the");  // 334
            list_name.Add("yen thuy");  // 335

            int random = new Random().Next(0, 313);
            return list_name[random];
        }
    }
}
