using System;
using System.Collections.Generic;

namespace PAYONEER.RandomData
{
    public class Answer_Question_Cate_04_PetName
    {
        public string Get_Name()
        {
            List<string> list_name = new List<string>();
            list_name.Add("buddy");  // 01
            list_name.Add("jake");  // 02
            list_name.Add("bailey");  // 03
            list_name.Add("rocky");  // 04
            list_name.Add("charlie");  // 05
            list_name.Add("jack");  // 06
            list_name.Add("toby");  // 07
            list_name.Add("cody");  // 08
            list_name.Add("buster");  // 09
            list_name.Add("duke");  // 10
            list_name.Add("cooper");  // 11
            list_name.Add("harley");  // 12
            list_name.Add("riley");  // 13
            list_name.Add("bear");  // 14
            list_name.Add("murphy");  // 15
            list_name.Add("lucky");  // 16
            list_name.Add("tucker");  // 17
            list_name.Add("oliver");  // 18
            list_name.Add("oscar");  // 19
            list_name.Add("winston");  // 20
            list_name.Add("teddy");  // 21
            list_name.Add("sammy");  // 22
            list_name.Add("rusty");  // 23
            list_name.Add("shadow");  // 24
            list_name.Add("gizmo");  // 25
            list_name.Add("zeus");  // 26
            list_name.Add("bentley");  // 27
            list_name.Add("baxter");  // 28
            list_name.Add("jackson");  // 29
            list_name.Add("bandit");  // 30
            list_name.Add("samson");  // 31
            list_name.Add("hunter");  // 32
            list_name.Add("rudy");  // 33
            list_name.Add("milo");  // 34
            list_name.Add("casey");  // 35
            list_name.Add("sparky");  // 36
            list_name.Add("joey");  // 37
            list_name.Add("beau");  // 38
            list_name.Add("louie");  // 39
            list_name.Add("dakota");  // 40
            list_name.Add("rocco");  // 41
            list_name.Add("bruno");  // 42
            list_name.Add("boomer");  // 43
            list_name.Add("maximus");  // 44
            list_name.Add("luke");  // 45
            list_name.Add("mickey");  // 46
            list_name.Add("romeo");  // 47
            list_name.Add("henry");  // 48
            list_name.Add("cosmo");  // 49
            list_name.Add("spike");  // 50
            list_name.Add("diesel");  // 51
            list_name.Add("chester");  // 52
            list_name.Add("otis");  // 53
            list_name.Add("tyson");  // 54
            list_name.Add("coco");  // 55
            list_name.Add("jasper");  // 56
            list_name.Add("pepper");  // 57
            list_name.Add("spencer");  // 58
            list_name.Add("scooter");  // 59
            list_name.Add("simba");  // 60
            list_name.Add("duncan");  // 61
            list_name.Add("simon");  // 62
            list_name.Add("peanut");  // 63
            list_name.Add("brutus");  // 64
            list_name.Add("prince");  // 65
            list_name.Add("chance");  // 66
            list_name.Add("george");  // 67
            list_name.Add("sampson");  // 68
            list_name.Add("bubba");  // 69
            list_name.Add("marley");  // 70
            list_name.Add("scout");  // 71
            list_name.Add("maxwell");  // 72
            list_name.Add("rurus");  // 73
            list_name.Add("elvis");  // 74
            list_name.Add("barney");  // 75
            list_name.Add("smokey");  // 76
            list_name.Add("chico");  // 77
            list_name.Add("kobe");  // 78
            list_name.Add("bosco");  // 79
            list_name.Add("blue");  // 80
            list_name.Add("brady");  // 81
            list_name.Add("oreo");  // 82
            list_name.Add("chase");  // 83
            list_name.Add("guinness");  // 84
            list_name.Add("snoopy");  // 85
            list_name.Add("champ");  // 86
            list_name.Add("dexter");  // 87
            list_name.Add("roscoe");  // 88
            list_name.Add("sebastian");  // 89
            list_name.Add("harry");  // 90
            list_name.Add("moose");  // 91
            list_name.Add("rascal");  // 92
            list_name.Add("molly");  // 93
            list_name.Add("bella");  // 94
            list_name.Add("lucy");  // 95
            list_name.Add("maggie");  // 96
            list_name.Add("daisy");  // 97
            list_name.Add("sadie");  // 98
            list_name.Add("chloe");  // 99
            list_name.Add("sophie");  // 100
            list_name.Add("lola");  // 101
            list_name.Add("abby");  // 102
            list_name.Add("ginger");  // 103
            list_name.Add("roxy");  // 104
            list_name.Add("gracie");  // 105
            list_name.Add("sasha");  // 106
            list_name.Add("angel");  // 107
            list_name.Add("lily");  // 108
            list_name.Add("princess");  // 109
            list_name.Add("emma");  // 110
            list_name.Add("rosie");  // 111
            list_name.Add("lady");  // 112
            list_name.Add("annie");  // 113
            list_name.Add("ruby");  // 114
            list_name.Add("missy");  // 115
            list_name.Add("katie");  // 116
            list_name.Add("madison");  // 117
            list_name.Add("zoey");  // 118
            list_name.Add("lilly");  // 119
            list_name.Add("penny");  // 120
            list_name.Add("belle");  // 121
            list_name.Add("samantha");  // 122
            list_name.Add("brandy");  // 123
            list_name.Add("holly");  // 124
            list_name.Add("sandy");  // 125
            list_name.Add("jasmine");  // 126
            list_name.Add("stella");  // 127
            list_name.Add("lexi");  // 128
            list_name.Add("shelby");  // 129
            list_name.Add("roxie");  // 130
            list_name.Add("heidi");  // 131
            list_name.Add("lulu");  // 132
            list_name.Add("misty");  // 133
            list_name.Add("honey");  // 134
            list_name.Add("maddie");  // 135
            list_name.Add("sassy");  // 136
            list_name.Add("dixie");  // 137
            list_name.Add("precious");  // 138
            list_name.Add("sydney");  // 139
            list_name.Add("luna");  // 140
            list_name.Add("cookie");  // 141
            list_name.Add("hannah");  // 142
            list_name.Add("sugar");  // 143
            list_name.Add("phoebe");  // 144
            list_name.Add("nikki");  // 145
            list_name.Add("amber");  // 146
            list_name.Add("maya");  // 147
            list_name.Add("cassie");  // 148
            list_name.Add("mocha");  // 149
            list_name.Add("chelsea");  // 150
            list_name.Add("baby");  // 151
            list_name.Add("nala");  // 152
            list_name.Add("pebbles");  // 153
            list_name.Add("ellie");  // 154
            list_name.Add("mandy");  // 155
            list_name.Add("jessie");  // 156
            list_name.Add("cleo");  // 157
            list_name.Add("trixie");  // 158
            list_name.Add("sierra");  // 159
            list_name.Add("cocoa");  // 160
            list_name.Add("isabella");  // 161
            list_name.Add("millie");  // 162
            list_name.Add("callie");  // 163
            list_name.Add("minnie");  // 164
            list_name.Add("abbey");  // 165
            list_name.Add("sheba");  // 166
            list_name.Add("bonnie");  // 167
            list_name.Add("gigi");  // 168
            list_name.Add("libby");  // 169
            list_name.Add("lacey");  // 170
            list_name.Add("tasha");  // 171
            list_name.Add("piper");  // 172
            list_name.Add("sophia");  // 173
            list_name.Add("muffin");  // 174
            list_name.Add("cali");  // 175
            list_name.Add("morgan");  // 176
            list_name.Add("haley");  // 177
            list_name.Add("lexie");  // 178
            list_name.Add("xena");  // 179
            list_name.Add("leia");  // 180
            list_name.Add("macy");  // 181
            list_name.Add("hazel");  // 182
            list_name.Add("fiona");  // 183
            list_name.Add("charlotte");  // 184
            list_name.Add("izzy");  // 185
            list_name.Add("josie");  // 186
            list_name.Add("ella");  // 187
            list_name.Add("athena");  // 188
            list_name.Add("thor");  // 189
            list_name.Add("rufus");  // 190
            list_name.Add("harper");  // 191
            list_name.Add("kona");  // 192
            list_name.Add("layla");  // 193
            list_name.Add("delilah");  // 194
            list_name.Add("grace");  // 195
            list_name.Add("gypsy");  // 196
            list_name.Add("mila");  // 197
            list_name.Add("olive");  // 198
            list_name.Add("nina");  // 199
            list_name.Add("nova");  // 200

            int random = new Random().Next(0, 199);
            return list_name[random];
        }
    }
}
